version: '3.8'

services:
  document_parser:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    stdin_open: true  # Keep the container open for interaction
    tty: true         # Allocate a pseudo-TTY for interaction
    entrypoint: ["python", "parse_documents.py"]  # Run the script when the container starts